# Generated by Django 2.1.2 on 2018-10-27 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodula2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adminstrative_name', models.CharField(max_length=200)),
                ('DateOfEstablish', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Principal_Phone', models.IntegerField()),
                ('Contact_no', models.IntegerField()),
                ('Adminstrative_type', models.CharField(max_length=100)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
