# Generated by Django 2.1.2 on 2018-10-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodula2',
            old_name='Principal_Phone',
            new_name='Principal_Phone_NO',
        ),
    ]
