# Generated by Django 2.1.2 on 2018-10-28 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_auto_20181027_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminmodula2',
            new_name='Profile',
        ),
    ]
