# Generated by Django 2.1.2 on 2018-10-29 05:53

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20181028_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Principal_Phone_NO',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
