# Generated by Django 2.1.2 on 2018-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
